### ISSUE TITLE
Lista de eventos (home)

### ISSUE THREAD

**Issue by perepinol** [perepinol/trainingwellApp#11]
Contiene info sobre:
* Nombre del evento
* Hora
* Lugar

**Comment by perepinol** [comment]
Pot interessar-nos fer una pagina extra de "detall d'esdeveniment" on es vegi tota la informació, el lloc on es fa i com anar-hi

**Comment by AleksSG** [comment]
Botón de 'Directions' en un evento lleva a una vista que no toca (sólo puede acceder Responsable)

**Comment by AleksSG** [comment]
Arreglado
