### ISSUE TITLE
Organizador cancela una reserva

### ISSUE THREAD

**Issue by Apseuma** [perepinol/trainingwellApp#3]
- Trigger: Reserva

- Precondiciones: Organizador debe tener una reserva hecha

- Interested stakeholders: Organizador, Responsable instalaciones

- Active stakeholders: Organizador

1. El sistema verifica que los dato introducidos por el organizador son correctos.
2. El sistema muestra por pantalla las reservas del usuario.
3. El sistema obtiene del usuario la reserva que quiere cancelar. 
4. El sistema muestra esta reserva y sus datos.
5. El sistema requiere una confirmación de cancelación.
6. El sistema borra la reserva.
7. El sistema cierra sesión.

**Como** organitzador
**quiero** cancelar una reserva
**para** suspender un evento deportivo.

**Comment by perepinol** [comment]
Pendiente de que se cree el detalle de reserva

**Comment by perepinol** [comment]
* La cancelación se hace con un GET, y debería ser un DELETE
* **No utilicéis objects.get con parámetros que introduce el usuario**. Si el resultado no existe, hay una excepción, y debería haber un 404. Utilitzad el shortcut get_object_or_404, o el custom decorator get_if_creator, que también lanza 401 si es necesario.
* Error al cancelar la reserva en el logger.info:
```
Exception Type: 	TypeError
Exception Value: 	must be str, not int
Exception Location: 	/eventApp/views.py in delete_reservation, line 348
logger.info("Reservation " + item.id + " changed status to " + Reservation.CANCELOUTTIME)
```
