### ISSUE TITLE
Tareas Cron

### ISSUE THREAD

**Issue by AleksSG** [perepinol/trainingwellApp#30]
Implementar tareas Cron que se ejecutan periódicamente como comprobar si ha pasado X días desde su soft-deleted para eliminarlo definitivamente.

Para ello, se debe crear una nueva función en cada uno de los modelos similar a la de borrar: marcar el boolean "deleted" a cierto.

**Comment by perepinol** [comment]
* Hard delete de todos los modelos (en caso de que haya pasado x tiempo desde el soft delete)
* Generación de informes mensuales

**Comment by AleksSG** [comment]
Borrar reservas (y facturas) a los 2 años de su creación

**Comment by perepinol** [comment]
* Borrar reserva si no está pagada en 1 día
