### ISSUE TITLE
Timezone support for schedule view

### ISSUE THREAD

**Issue by perepinol** [perepinol/trainingwellApp#41]

**Comment by AleksSG** [comment]
Per arreglar-ho es necessita aquests settings.py:
TIME_ZONE = 'Europe/Madrid'
USE_TZ = False

Això comporta que no es puguin confirmar reserves. Després de seleccionar els timeblocs i efectuar el POST per confirmar, la resposta del POST és 400: Bad Request: /events/reservation/new
Es necessita REVISIÓ

Tanmateix hi ha un petit bug a l'hora de calcular el canvi de mes (dia 30 de abril + 2 dies => dia 2 de abril).
