### ISSUE TITLE
Vista de incidencias

### ISSUE THREAD

**Issue by perepinol** [perepinol/trainingwellApp#46]
(Pendiente de rellenar después de la entrevista)

**Comment by AleksSG** [comment]
El responsable de instalaciones puede crear Incidencias (modelo) con los campos: Nombre, Descripción, Fecha límite para solucionar, Opcional Campos relacionados, Deshabilitar campo.

Estas incidencias únicamente el responsable de instalaciones tiene acceso a ellas por los métodos Create, Read, Delete (opcional, se pueden borrar una vez supere la fecha límite).

PS. Comportará cambios en la hora de reservar. Si un campo está "deshabilitado" mediante una incidencia, éste no aparecerá como disponible para futuras reservas.
