### ISSUE TITLE
Vista de eventos

### ISSUE THREAD

**Issue by perepinol** [perepinol/trainingwellApp#51]

**Comment by AleksSG** [comment]
En general em sembla correcte. Un parell de consideracions:
En quant a 'Search' estaria bé (per propera iteració) si no es massa complicat. Els requisits són "obtindre tot el calendari d'esdeveniments" i "veure l'espai que toca en un esdeveniment en una hora en concret". Per tant no és algo prioritari pero es d'ajut per obrir un esdeveniment més ràpid.
Per altra banda, el responsive design en dispositius petits queda malament. Adaptar un calendari és molt difícil, i més si s'ha de visualitzar tot. Què fem? Ho deixem per ara i "ho tractem" més endavant?

Per lo altre està bé, tanco la issue i faig el merge amb els conflicts, i si fa falta la reobrirem per futura iteració.
