### ISSUE TITLE
Mejorar estilos

### ISSUE THREAD

**Issue by perepinol** [perepinol/trainingwellApp#52]

**Comment by AleksSG** [comment]
En mostrar Reservas, controlar el 'margin'. En navegador Safari no se visualiza.
En mostrar Reservas, cambiar el color de las Reservas según su 'estado'.
En detalle Reservas, agrupar horas consecutivas.
En crear Reserva, mostrar de diferente color las horas seleccionadas.
En la confirmación de crear Reserva, agrupar horas conssecutivas.

**Comment by perepinol** [comment]
Marcar espacios seleccionados en schedule view

**Comment by Apseuma** [comment]
Añadir footer
Añadir sombreados

**Comment by Apseuma** [comment]
Usar colores de bootstrap

**Comment by AleksSG** [comment]
Mostrar descripción de las pistas como Popover a la hora de reservar. Esperando BBDD
