### ISSUE TITLE
Vista de horario con las horas ocupadas y disponibles

### ISSUE THREAD

**Issue by perepinol** [perepinol/trainingwellApp#9]
* Las celdas deben ser botones

**Comment by perepinol** [comment]
Suposar que al fer el render de la pàgina es té el següent context:

```
{
    ...,
    'event': {
        'name': <nom de l'event>,
        'date': <data de l'event>,
        'space_type': <un dels tipus a FIELD_OPTIONS>
    }
}
```

**Comment by AleksSG** [comment]
En el contexto se debe incluir un dato 'num_spaces':
`{
    ...,
    'event': {
        ...,
        'num_spaces0: <integer>
    }
}`

**Comment by AleksSG** [comment]
![WhatsApp Image 2020-04-01 at 10 31 13](https://user-images.githubusercontent.com/36915847/78117297-c95a0580-7405-11ea-9378-38837f04c00d.jpeg)

**Comment by AleksSG** [comment]
![WhatsApp Image 2020-04-01 at 10 44 51](https://user-images.githubusercontent.com/36915847/78118020-a845e480-7406-11ea-8d42-b967be8e4d6e.jpeg)
